import { pageInformation, Routes } from './pages'
import tempsoUX from '@/images/ux-case-study-tempso.png'
import containerManagement from '@/images/case-study-container-management.png'
import checkoutFlow from '@/images/case-study-payment-plan.png'




export const caseStudies = [
    {
        key: 'tempso',
        client: 'Tempso',
        year: '2019',
        platform: 'native (IOS & ANDROID)',
        title: 'Designing a Classical Music Streaming App',
        description:
            'Designed a classical music streaming application fully integrated with Apple Music and Spotify.',
        href: pageInformation[Routes.Tempso]!.path,
        src: tempsoUX,
        alt: 'Tempso UX Case Study',
        external: false,
        projectType: 'design',
        metrics: [
            '2020',
            'user research, user experience, user interface',
            'user interviews, wireframing, usability studies',
            'native IOS & android',
            'miro mindmapping, octopus sitemap, figma',
        ],
        latest: true,
    },
    {
        key: 'bluecargo_dashboard',
        client: 'BlueCargo',
        year: '2022',
        platform: 'desktop',
        title: 'Designing a Container Management Dashboard',
        description:
            'Designed a dashboard for Supply Chain professionals, where they can follow the status of their containers at the ports of Los Angeles and Long Beach.',
        href: pageInformation[Routes.ContainerDashboard]!.path,
        src: containerManagement,
        alt: 'Container Tracking Case Study',
        external: false,
        projectType: 'design',
        metrics: [
            '2020',
            'user research, user experience, user interface',
            'user interviews, wireframing, usability studies',
            'native IOS & android',
            'miro mindmapping, octopus sitemap, figma',
        ],
        latest: true,
    },
    {
        key: 'bluecargo_payment',
        client: 'BlueCargo',
        year: '2022',
        platform: 'desktop',
        title: 'Designing a checkout flow',
        description:
            'Designed a checkout flow for a Supply Chain software, where users have a choice between three plans, and can adjust their volume per plan.',
        href: pageInformation[Routes.CheckoutFlow]!.path,
        src: checkoutFlow,
        alt: 'Checkout Flow Case Study',
        external: false,
        projectType: 'design',
        metrics: [
            '2021',
            'user experience, user interface',
            'wireframing',
            'desktop',
            'flow charts, figma',
        ],
        latest: true,
    },
    {
        key: 'kbwf',
        client: 'Know Better World Foundation',
        year: '2020',
        platform: 'desktop',
        title: 'Designing and building a website for a Foundation',
        description:
            'Designed and build a website for a foundation emporing women to become entrepeneur.',
        href: 'https://www.knowbetterworldfoundation.org/',
        src: '/case-study-kbwf.png',
        alt: 'Know Better World Foundation Website',
        external: true,
        projectType: 'design',
        metrics: [
            '2020',
            'user research, user experience, user interface',
            'user interviews, wireframing, usability studies',
            'native IOS & android',
            'miro mindmapping, octopus sitemap, figma',
        ],
        latest: false,
    },
    {
        key: 'ui_shots',
        client: 'UI Shots',
        year: '2020',
        platform: 'desktop and mobile',
        title: '100 days of UI Challenge',
        description: 'Designed UI shots to explore different design universe.',
        href: pageInformation[Routes.UIShots]!.path,
        src: '/case-study-ui-shots.png',
        alt: 'UI Shots',
        external: false,
        projectType: 'design',
        metrics: [
            '2020',
            'user research, user experience, user interface',
            'user interviews, wireframing, usability studies',
            'native IOS & android',
            'miro mindmapping, octopus sitemap, figma',
        ],
        latest: false,
    },
    {
        key: 'portfolio_website',
        client: 'Portfolio Website',
        year: '2022',
        platform: 'responsive web',
        title: 'Designed and built my own portfolio website.',
        description:
            'Designed and built the front-end and back-end of my portfolio website using Next.js, React.js, Node.js, Tailwind CSS, Mongoose and MongodB.',
        href: 'https://github.com/PierreParienteDimitrov/pierre-parientedimitrov',
        src: '/software-portfolio.png',
        alt: 'Portfolio Website',
        external: true,
        projectType: 'design',
        metrics: [
            '2020',
            'user research, user experience, user interface',
            'user interviews, wireframing, usability studies',
            'native IOS & android',
            'miro mindmapping, octopus sitemap, figma',
        ],
        latest: false,
    },
    {
        key: 'tempso_website',
        client: 'Tempso Landing Page',
        year: '2021',
        platform: 'responsive web',
        title: 'Designed and built Tempso landing page.',
        description:
            'Designed and built Tempso landing page using Next.js, React.js and Tailwind CSS.',
        href: 'https://github.com/PierreParienteDimitrov/tempso.com',
        src: '/case-study-tempso-landing-page.png',
        alt: 'Tempso Landing Page',
        external: true,
        projectType: 'software',
        metrics: [
            '2020',
            'user research, user experience, user interface',
            'user interviews, wireframing, usability studies',
            'native IOS & android',
            'miro mindmapping, octopus sitemap, figma',
        ],
        latest: false,
    },
]
